#########################################################################################################################
############################################# Basic Configuration Begin #################################################
server:
  port: 1003
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
#    H2数据库
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    schema: classpath:data/schema.sql
    data: classpath:data/data.sql
    driver-class-name: org.h2.Driver
#    Spring Boot 2.x默认连接池Hikari
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    loadbalancer:
      retry:
#        启用Spring重试机制，在Ribbon进行重试时需要开启此配置
        enabled: true
  sleuth:
    sampler:
#      Sleuth采集率，1表示采集率100%，0.1表示10%，以此类推
      probability: 1F
############################################# Basic Configuration End ###################################################
#########################################################################################################################

#########################################################################################################################
############################################# Actuator Configuration Begin ##############################################
management:
  endpoints:
    web:
      exposure:
#        允许所有端点访问，在生产环境中需更细粒度的配置
        include: "*"
  endpoint:
    health:
#      显示详细的监控信息，取值选项：NEVER，WHEN_AUTHORIZED，ALWAYS
      show-details: ALWAYS
############################################# Actuator Configuration End ################################################
#########################################################################################################################

#########################################################################################################################
############################################# Eureka Configuration Begin ################################################
eureka:
  client:
    service-url:
#      配置Eureka服务端地址并注册，若服务端是高可用环境，需要配置多个服务端地址并使用逗号分隔
      defaultZone: http://eureka:123456@localhost:8761/eureka/
    healthcheck:
#    增加actuator健康检查，需要引入actuator依赖
      enabled: true
  instance:
#    配置Eureka客户端实例ID，这里设置为ip:port
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#    是否使用IP设置hostName属性
#    prefer-ip-address: true
#    状态页面的URL，相对路径，默认使用HTTP访问，如果需要使用HTTPS则需要使用绝对路径配置（eureka.instance.status-page-url）
#    status-page-url-path: /
#    配置Eureka客户端实例发送给Eureka服务端的心跳频率，默认30S，生产环境中建议使用默认值
#    lease-renewal-interval-in-seconds: 5
#    配置Eureka服务端至上次收到Eureka客户端的心跳之后，等待下一次心跳的超时时间，若超过这个时间，则移除该Eureka客户端实例，默认90S，生产环境中建议使用默认值
#    lease-expiration-duration-in-seconds: 15
############################################# Eureka Configuration End ##################################################
#########################################################################################################################

#########################################################################################################################
############################################# Ribbon Configuration Begin ################################################
#配置指定的Eureka客户端实例请在ribbon前加上实例名
ribbon:
#  请求链接超时时间
  ConnectTimeout: 1000
#  请求处理超时时间
  ReadTimeout: 3000
#  对当前服务实例重试次数，需要引入spring-retry依赖
  MaxAutoRetries: 1
#  切换服务实例重试次数
  MaxAutoRetriesNextServer: 3
#  对所有操作请求都进行重试：GET、POST、PUT等等
  OkToRetryOnAllOperations : true
############################################# Ribbon Configuration End ##################################################
#########################################################################################################################

#########################################################################################################################
############################################# Feign Configuration Begin #################################################
feign:
  compression:
    request:
#      使用GZIP压缩请求数据
      enabled: true
    response:
#      使用GZIP压缩响应数据
      enabled: true
  client:
    config:
#      配置指定的Eureka客户端实例请将default换成实例名
      default:
#        日志输出级别：none、basic、headers、full，需要配置logging.level.{FeignClient包地址}:DEBUG
        loggerLevel: none
  hystrix:
#    开启对熔断的支持
    enabled: true
############################################# Feign Configuration End ###################################################
#########################################################################################################################

#########################################################################################################################
############################################# Hystrix Configuration Begin ###############################################
hystrix:
  command:
#    配置指定的Eureka客户端实例请将default换成实例名
    default:
      execution:
        isolation:
#          隔离策略
#          THREAD（默认）：线程隔离，在单独的线程上执行，并发请求受线程池大小的控制
#          优点：存在超时机制
#          缺点：线程切换和调度存在一定开销
#          SEMAPHORE：信号量隔离，在调用线程上执行，并发请求受信号量计数器的限制
#          优点：没有线程切换的开销
#          缺点：没有超时机制
          strategy: THREAD
          thread:
#            执行熔断处理的超时时间，该值应该大于（ribbon.ReadTimeout*ribbon.MaxAutoRetriesNextServer），否则ribbon配置效果未执行完之前便已触发熔断，单位MS
            timeoutInMilliseconds: 10000
############################################# Hystrix Configuration End #################################################
#########################################################################################################################
